### ISSUE TITLE
a11y audit fixes

### ISSUE THREAD

**Issue by carylwyatt** [hathitrust/mdp-web#4]
- [x] [1727272](https://axeauditor.dequecloud.com/test-run/b2613a94-fe0b-11ee-96ce-dfcb37e53e3c/issue/86d90230-fe29-11ee-966d-f39062522b3f?viewMode=issues&sortField=ordinal&sortDir=asc&filter%5Bcomponent_number%5D=4&row=1) screen reader can't tell if search result facet accordions are in expanded or collapsed state
  - fix:  the [accordion is part of the mdp-web skeleton](https://github.com/hathitrust/mdp-web/blob/66457b4c16c994ef418fa451066ae72864f103ca/firebird/skeleton.xsl#L227-L234). it's already setting aria-expanded=true if the accordion is open but we also need to set aria-expanded=false if not open. the upside to this being in mdp-web is that it will fix the issue for mb at the same time.

**Comment by angelinanz** [comment]
This is also captured in [DEV-1172] 

[DEV-1172]: https://hathitrust.atlassian.net/browse/DEV-1172?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by aelkiss** [comment]
This is staged on test.babel.hathitrust.org

**Comment by carylwyatt** [comment]
Deployed yesterday via PR #5
